config/routes.rb
Poker::Application.routes.draw do

  root 'static_pages#home'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
	match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
	resources :users
	resources :sessions, only: [:new, :create, :destroy]
	
	match '/tables/server_time', to: 'tables#server_time', via: 'get'
	
	resources :tables do
		member do
			get 'players_info'
			post 'post_protagonist_cards'
			get 'status'
			post 'join'
			get 'leave'
			get 'ready'
			get 'fold'
			get 'sitout'
			get 'join_table_details'
			
		end
	end
	

end

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_signup_link.html.erb
<% if signed_in? %>
	<p>Welcome back, <%= current_user.name %>!</p>
	<% if current_table %>
		<p>to do - return to multiple tables at once</p>
		<%= link_to "Return to table", table_path(current_table.first.id), class: "btn btn-large btn-primary" %>
	<% else %>
		<%= link_to "Find a game now!", tables_path, class: "btn btn-large btn-primary" %>
	<% end %>
<% else %> 
	</br>
	<div><%= link_to "Try it now!", "#", class: "btn btn-large btn-primary" %></div>
	</br>
	<div>
		<%= link_to "Create an account", new_user_path, class: "btn btn-large btn-primary" %>
		<p class="subtext">Already have an account? Sign in now.</p>
	</div>
<% end %>