config/routes.rb
Poker::Application.routes.draw do

  root 'static_pages#home'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
	match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
	resources :users
	resources :sessions, only: [:new, :create, :destroy]
	
	match '/tables/server_time', to: 'tables#server_time', via: 'get'
	
	resources :tables do
		member do
			get 'players_info'
			post 'post_protagonist_cards'
			get 'status'
			post 'join'
			get 'leave'
			get 'ready'
			get 'fold'
			get 'sitout'
			get 'join_table_details'
			
		end
	end
	

end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-default navbar-inverse" role="navigation">
	<div class="container-fluid">
		<%= link_to "Kai's Chinese Poker", root_url, id: "logo" %>
		<nav>
			<ul class="navbar-nav nav navbar-right">
				<li><%= link_to "Home", root_path %></li>
				<li><%= link_to "Tutorial", help_path %></li>
				<li><%= link_to "Tables", tables_path %></li>
				<% if signed_in? %>
					<li><%= link_to "Users", users_path %></li>
					<li id="fat-menu" class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">
							Account <b class="caret"></b>
						</a>
						<ul class="dropdown-menu">
							<li><%= link_to "Profile", current_user %></li>
							<li><%= link_to "Settings",  edit_user_path(current_user) %></li>
							<li class="divider"></li>
							<li>
								<%= link_to "Sign out", signout_path, method: "delete" %>
							</li>
						</ul>
					</li>
				<% else %>
					<li><%= link_to "Sign in", signin_path %></li>
				<% end %>
			</ul>
		</nav>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<%= render 'layouts/header' %>
	<div class="container-fluid">
		<% flash.each do |key, value| %>
			<%= content_tag(:div, value, class: "alert alert-#{key}") %>
		<% end %>
		<%= yield %>
	</div>
</body>
</html>